name: Trello Automation

on:
  schedule:
    # Daily reset: 11:00 PM MDT (05:00 UTC next day)
    - cron: '0 5 * * *'
    # Weekly cards: Fridays 11:00 PM MDT (05:00 UTC Saturday)
    - cron: '0 5 * * 6'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  reset-daily-tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build trello client
      run: go build -o trello-client

    - name: Refresh cache first
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
      run: ./trello-client --refresh

    - name: Sync Canvas assignments
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
        CANVAS_API_TOKEN: ${{ secrets.CANVAS_API_TOKEN }}
        CANVAS_BASE_URL: https://alpine.instructure.com
      run: ./trello-client --sync-canvas

    - name: Sync MHA assignments from Moodle
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
        MOODLE_WSTOKEN: ${{ secrets.MOODLE_WSTOKEN }}
        MOODLE_BASE_URL: https://ohsu.mrooms3.net
      run: ./trello-client --sync-moodle

    - name: Run daily reset
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
      run: ./trello-client --daily-reset