name: Weekly Card Creation

on:
  # Scheduled runs disabled temporarily; trigger manually via Actions tab.
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  create-weekly-cards:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build trello client
      run: go build -o trello-client

    - name: Refresh cache first
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
      run: ./trello-client --refresh

    - name: Create weekly cards
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
      run: ./trello-client --create-weekly
